Fix building with UNICODE
Use the unicode version of `RegOpenKeyEx` to avoid compilation error caused by string type like:

```
../../node/deps/cares/src/lib/ares_event_configchg.c(322,9): error: incompatible pointer types passing 'char[62]' to parameter of type 'LPCWSTR' (aka 'const unsigned short *') [-Werror,-Wincompatible-pointer-types]
  322 |         "SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces",
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```