ares_getnameinfo: Add missing iphlpapi.h include
Fixes mingw-w64 build error

ares_getnameinfo.c:357:9: error: implicit declaration of function 'if_indextoname' [-Werror=implicit-function-declaration]